[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit GFX Library
  fastled/FastLED

build_flags =
  -DMATRIX_WIDTH=128
  -DMATRIX_HEIGHT=64
  -DCHAIN_LENGTH=1
  
upload_speed = 921600

